-- MySQL Script generated by MySQL Workbench
-- 02/26/16 16:25:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aggressiveShower
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aggressiveShower` ;

-- -----------------------------------------------------
-- Schema aggressiveShower
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aggressiveShower` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `aggressiveShower` ;

-- -----------------------------------------------------
-- Table `aggressiveShower`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aggressiveShower`.`users` ;

CREATE TABLE IF NOT EXISTS `aggressiveShower`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `userName` VARCHAR(45) NOT NULL COMMENT '',
  `firstName` VARCHAR(255) NOT NULL COMMENT '',
  `lastName` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` DATE NOT NULL COMMENT '',
  `updated_at` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aggressiveShower`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aggressiveShower`.`departments` ;

CREATE TABLE IF NOT EXISTS `aggressiveShower`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aggressiveShower`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aggressiveShower`.`groups` ;

CREATE TABLE IF NOT EXISTS `aggressiveShower`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `departments_has_users_departments_id` INT NOT NULL COMMENT '',
  `departments_has_users_users_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `departments_has_users_departments_id`, `departments_has_users_users_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aggressiveShower`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aggressiveShower`.`files` ;

CREATE TABLE IF NOT EXISTS `aggressiveShower`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `URI` VARCHAR(255) NOT NULL COMMENT '',
  `cerated_at` DATE NULL COMMENT '',
  `users_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `users_id`)  COMMENT '',
  INDEX `fk_files_users1_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_files_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aggressiveShower`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aggressiveShower`.`departments_has_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aggressiveShower`.`departments_has_files` ;

CREATE TABLE IF NOT EXISTS `aggressiveShower`.`departments_has_files` (
  `departments_id` INT NOT NULL COMMENT '',
  `files_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`departments_id`, `files_id`)  COMMENT '',
  INDEX `fk_departments_has_files_files1_idx` (`files_id` ASC)  COMMENT '',
  INDEX `fk_departments_has_files_departments_idx` (`departments_id` ASC)  COMMENT '',
  CONSTRAINT `fk_departments_has_files_departments`
    FOREIGN KEY (`departments_id`)
    REFERENCES `aggressiveShower`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_files_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `aggressiveShower`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aggressiveShower`.`departments_has_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aggressiveShower`.`departments_has_groups` ;

CREATE TABLE IF NOT EXISTS `aggressiveShower`.`departments_has_groups` (
  `departments_id` INT NOT NULL COMMENT '',
  `groups_id` INT NOT NULL COMMENT '',
  `groups_departments_has_users_departments_id` INT NOT NULL COMMENT '',
  `groups_departments_has_users_users_id` INT NOT NULL COMMENT '',
  `users_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`departments_id`, `groups_id`, `groups_departments_has_users_departments_id`, `groups_departments_has_users_users_id`, `users_id`)  COMMENT '',
  INDEX `fk_departments_has_groups_groups1_idx` (`groups_id` ASC, `groups_departments_has_users_departments_id` ASC, `groups_departments_has_users_users_id` ASC)  COMMENT '',
  INDEX `fk_departments_has_groups_departments1_idx` (`departments_id` ASC)  COMMENT '',
  INDEX `fk_departments_has_groups_users1_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_departments_has_groups_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `aggressiveShower`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_groups_groups1`
    FOREIGN KEY (`groups_id` , `groups_departments_has_users_departments_id` , `groups_departments_has_users_users_id`)
    REFERENCES `aggressiveShower`.`groups` (`id` , `departments_has_users_departments_id` , `departments_has_users_users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_groups_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aggressiveShower`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
